// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/job.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/job.proto

It has these top-level messages:
	InitReq
	InitResp
	RunReq
	RunResp
	LogReq
	LogResp
	LogStreamReq
	LogStreamResp
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_init     JobStatus = 0
	JobStatus_running  JobStatus = 1
	JobStatus_finished JobStatus = 2
)

var JobStatus_name = map[int32]string{
	0: "init",
	1: "running",
	2: "finished",
}
var JobStatus_value = map[string]int32{
	"init":     0,
	"running":  1,
	"finished": 2,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InitReq struct {
}

func (m *InitReq) Reset()                    { *m = InitReq{} }
func (m *InitReq) String() string            { return proto.CompactTextString(m) }
func (*InitReq) ProtoMessage()               {}
func (*InitReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InitResp struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *InitResp) Reset()                    { *m = InitResp{} }
func (m *InitResp) String() string            { return proto.CompactTextString(m) }
func (*InitResp) ProtoMessage()               {}
func (*InitResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InitResp) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RunReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *RunReq) Reset()                    { *m = RunReq{} }
func (m *RunReq) String() string            { return proto.CompactTextString(m) }
func (*RunReq) ProtoMessage()               {}
func (*RunReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RunReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RunResp struct {
}

func (m *RunResp) Reset()                    { *m = RunResp{} }
func (m *RunResp) String() string            { return proto.CompactTextString(m) }
func (*RunResp) ProtoMessage()               {}
func (*RunResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type LogReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *LogReq) Reset()                    { *m = LogReq{} }
func (m *LogReq) String() string            { return proto.CompactTextString(m) }
func (*LogReq) ProtoMessage()               {}
func (*LogReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LogResp struct {
	Lines  []string  `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
	Status JobStatus `protobuf:"varint,2,opt,name=status,enum=api.JobStatus" json:"status,omitempty"`
}

func (m *LogResp) Reset()                    { *m = LogResp{} }
func (m *LogResp) String() string            { return proto.CompactTextString(m) }
func (*LogResp) ProtoMessage()               {}
func (*LogResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogResp) GetLines() []string {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *LogResp) GetStatus() JobStatus {
	if m != nil {
		return m.Status
	}
	return JobStatus_init
}

type LogStreamReq struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *LogStreamReq) Reset()                    { *m = LogStreamReq{} }
func (m *LogStreamReq) String() string            { return proto.CompactTextString(m) }
func (*LogStreamReq) ProtoMessage()               {}
func (*LogStreamReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogStreamReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LogStreamResp struct {
	Line string `protobuf:"bytes,1,opt,name=line" json:"line,omitempty"`
}

func (m *LogStreamResp) Reset()                    { *m = LogStreamResp{} }
func (m *LogStreamResp) String() string            { return proto.CompactTextString(m) }
func (*LogStreamResp) ProtoMessage()               {}
func (*LogStreamResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *LogStreamResp) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func init() {
	proto.RegisterType((*InitReq)(nil), "api.InitReq")
	proto.RegisterType((*InitResp)(nil), "api.InitResp")
	proto.RegisterType((*RunReq)(nil), "api.RunReq")
	proto.RegisterType((*RunResp)(nil), "api.RunResp")
	proto.RegisterType((*LogReq)(nil), "api.LogReq")
	proto.RegisterType((*LogResp)(nil), "api.LogResp")
	proto.RegisterType((*LogStreamReq)(nil), "api.LogStreamReq")
	proto.RegisterType((*LogStreamResp)(nil), "api.LogStreamResp")
	proto.RegisterEnum("api.JobStatus", JobStatus_name, JobStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Job service

type JobClient interface {
	Init(ctx context.Context, in *InitReq, opts ...grpc.CallOption) (*InitResp, error)
	Run(ctx context.Context, in *RunReq, opts ...grpc.CallOption) (*RunResp, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Init(ctx context.Context, in *InitReq, opts ...grpc.CallOption) (*InitResp, error) {
	out := new(InitResp)
	err := grpc.Invoke(ctx, "/api.Job/Init", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Run(ctx context.Context, in *RunReq, opts ...grpc.CallOption) (*RunResp, error) {
	out := new(RunResp)
	err := grpc.Invoke(ctx, "/api.Job/Run", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Job service

type JobServer interface {
	Init(context.Context, *InitReq) (*InitResp, error)
	Run(context.Context, *RunReq) (*RunResp, error)
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Job/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Init(ctx, req.(*InitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Job/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Run(ctx, req.(*RunReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Job_Init_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Job_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/job.proto",
}

// Client API for Log service

type LogClient interface {
	Get(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogResp, error)
	GetStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (Log_GetStreamClient, error)
}

type logClient struct {
	cc *grpc.ClientConn
}

func NewLogClient(cc *grpc.ClientConn) LogClient {
	return &logClient{cc}
}

func (c *logClient) Get(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogResp, error) {
	out := new(LogResp)
	err := grpc.Invoke(ctx, "/api.Log/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) GetStream(ctx context.Context, in *LogStreamReq, opts ...grpc.CallOption) (Log_GetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Log_serviceDesc.Streams[0], c.cc, "/api.Log/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &logGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Log_GetStreamClient interface {
	Recv() (*LogStreamResp, error)
	grpc.ClientStream
}

type logGetStreamClient struct {
	grpc.ClientStream
}

func (x *logGetStreamClient) Recv() (*LogStreamResp, error) {
	m := new(LogStreamResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Log service

type LogServer interface {
	Get(context.Context, *LogReq) (*LogResp, error)
	GetStream(*LogStreamReq, Log_GetStreamServer) error
}

func RegisterLogServer(s *grpc.Server, srv LogServer) {
	s.RegisterService(&_Log_serviceDesc, srv)
}

func _Log_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Log/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Get(ctx, req.(*LogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogStreamReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServer).GetStream(m, &logGetStreamServer{stream})
}

type Log_GetStreamServer interface {
	Send(*LogStreamResp) error
	grpc.ServerStream
}

type logGetStreamServer struct {
	grpc.ServerStream
}

func (x *logGetStreamServer) Send(m *LogStreamResp) error {
	return x.ServerStream.SendMsg(m)
}

var _Log_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Log_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _Log_GetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/job.proto",
}

func init() { proto.RegisterFile("api/job.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4e, 0xf2, 0x30,
	0x14, 0xc7, 0xd9, 0xc6, 0xc7, 0xd8, 0x61, 0x23, 0x7c, 0x27, 0x5e, 0x2c, 0xbb, 0x30, 0xa4, 0x46,
	0x43, 0xbc, 0x40, 0x82, 0x89, 0xaf, 0x40, 0x24, 0x5c, 0x98, 0xf2, 0x04, 0x5b, 0xa8, 0xf3, 0x18,
	0x6d, 0xcb, 0xda, 0xbd, 0xbf, 0x69, 0x37, 0x91, 0x28, 0x77, 0xe7, 0x9c, 0xff, 0x6f, 0x3b, 0xed,
	0xaf, 0x90, 0x95, 0x9a, 0x1e, 0xde, 0x55, 0xb5, 0xd4, 0x8d, 0xb2, 0x0a, 0xa3, 0x52, 0x13, 0x4b,
	0x20, 0x7e, 0x96, 0x64, 0xb9, 0x38, 0xb2, 0x02, 0xc6, 0x5d, 0x69, 0x34, 0x4e, 0x21, 0xa4, 0x43,
	0x1e, 0xcc, 0x83, 0x45, 0xc6, 0x43, 0x3a, 0xb0, 0x1c, 0x46, 0xbc, 0x95, 0x5c, 0x1c, 0xff, 0x24,
	0x09, 0xc4, 0x3e, 0x31, 0xda, 0x41, 0x3b, 0x55, 0x5f, 0x82, 0x36, 0x10, 0xfb, 0xc4, 0x68, 0xbc,
	0x82, 0x7f, 0x1f, 0x24, 0x85, 0xc9, 0x83, 0x79, 0xb4, 0x48, 0x78, 0xd7, 0xe0, 0x1d, 0x8c, 0x8c,
	0x2d, 0x6d, 0x6b, 0xf2, 0x70, 0x1e, 0x2c, 0xa6, 0xeb, 0xe9, 0xb2, 0xd4, 0xb4, 0xdc, 0xaa, 0x6a,
	0xef, 0xa7, 0xbc, 0x4f, 0xd9, 0x35, 0xa4, 0x3b, 0x55, 0xef, 0x6d, 0x23, 0xca, 0xcf, 0x4b, 0x8b,
	0x6e, 0x20, 0x3b, 0xcb, 0x8d, 0x46, 0x84, 0xa1, 0xdb, 0xe0, 0x91, 0x84, 0xfb, 0xfa, 0x7e, 0x05,
	0xc9, 0xe9, 0xcf, 0x38, 0x86, 0x21, 0x49, 0xb2, 0xb3, 0x01, 0x4e, 0x20, 0x6e, 0x5a, 0x29, 0x49,
	0xd6, 0xb3, 0x00, 0x53, 0x18, 0xbf, 0x92, 0x24, 0xf3, 0x26, 0x0e, 0xb3, 0x70, 0xfd, 0x02, 0xd1,
	0x56, 0x55, 0x78, 0x0b, 0x43, 0x67, 0x08, 0x53, 0x7f, 0xba, 0xde, 0x5b, 0x91, 0x9d, 0x75, 0x46,
	0xb3, 0x01, 0x32, 0x88, 0x78, 0x2b, 0x71, 0xe2, 0xe7, 0x9d, 0xb6, 0x22, 0xfd, 0x69, 0x1c, 0xb3,
	0x2e, 0x21, 0xda, 0xa9, 0xda, 0xa1, 0x1b, 0x61, 0x7b, 0xb4, 0x93, 0xd7, 0xa3, 0xbd, 0x2f, 0x36,
	0xc0, 0x27, 0x48, 0x36, 0xc2, 0x76, 0x77, 0xc2, 0xff, 0xdf, 0xe1, 0xc9, 0x41, 0x81, 0xbf, 0x47,
	0xee, 0xab, 0x55, 0x50, 0x8d, 0xfc, 0x33, 0x3f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x23,
	0xcf, 0xb6, 0xf7, 0x01, 0x00, 0x00,
}
